name: Build Data

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Packages ðŸ›Ž
              uses: actions/checkout@v2
              with:
                  path: './editor-packages'

            - name: Checkout Editor ðŸ›Ž
              uses: actions/checkout@v2
              with:
                  repository: 'bridge-core/editor'
                  ref: 'dev'
                  path: './editor'
                  fetch-depth: 0

            - name: Setup Deno ðŸš§
              uses: denolib/setup-deno@v2
              with:
                  deno-version: v1.12.X

            - name: Build data ðŸ”§
              run: |
                  ls
                  cd ./editor-packages
                  deno run -A --import-map=importMap.json ./scripts/build.ts
                  mv packages.zip ../editor/public
                  cd ../editor
                  ls

            - name: Commit files âœ…
              run: |
                  git config --local user.email "action@github.com"
                  git config --local user.name "GitHub Action"
                  git add -A && git commit -m "Updated data packages"

            - name: Push changes ðŸ”¼
              uses: ad-m/github-push-action@v0.6.0
              with:
                  repository: 'bridge-core/editor'
                  branch: 'dev'
                  github_token: ${{ secrets.EDITOR_DATA_PACKAGES }}
