name: Build Data

on:
    push:
        branches:
            - refactor
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Packages ðŸ›Ž
              uses: actions/checkout@v2
              with:
                  path: './editor-packages'
                  persist-credentials: false

            - name: Checkout Packages Release ðŸš€
              uses: actions/checkout@v2
              with:
                  path: './editor-packages-release'
                  ref: 'release'
                  persist-credentials: false

            - name: Setup Deno ðŸš§
              uses: denolib/setup-deno@v2
              with:
                  deno-version: v1.37.X

            - name: Build data ðŸ”§
              run: |
                  cd ./editor-packages
                  deno task build
                  mv packages.zip ../editor-packages-release/
                  mv hash ../editor-packages-release/

            - name: Commit files âœ…
              run: |
                  cd ./editor-packages-release
                  git config --local user.email "${{ github.event.pusher.email }}"
                  git config --local user.name "${{ github.event.pusher.name }}"
                  git add -A && git commit -m "${{ github.event.head_commit.message }}"

            - name: Push changes ðŸ”¼
              uses: ad-m/github-push-action@v0.6.0
              with:
                  directory: './editor-packages-release'
                  repository: 'bridge-core/editor-packages'
                  branch: 'release'
                  github_token: ${{ secrets.EDITOR_DATA_PACKAGES }}
