name: Run Unit Tests

on:
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Packages ğŸ›
              uses: actions/checkout@v2
              with:
                  path: './editor-packages'
                  persist-credentials: false

            - name: Setup Deno ğŸš§
              uses: denolib/setup-deno@v2
              with:
                  deno-version: v1.37.X

            - name: Run Unit Tests ğŸ”§
              run: |
                  cd ./editor-packages
                  deno task test-silent
